/**
 * BibleTextService — on-demand multi-translation loader.
 *
 * Resolution order for `loadTranslationBooks(id)`:
 *   1. Bundled/local dataset (`LocalBibleRepository` over the bundled JSON).
 *   2. Download-on-demand cache (`bible-dataset-cache`) — only hits when the
 *      checksum still matches the catalogued one.
 *   3. null — the dataset is not available locally; call
 *      `downloadAndLoadTranslationBooks` to fetch it explicitly.
 *
 * The catalogue of remote datasets is the static `data/bible/dataset-catalog.json`
 * (generated by `scripts/bible/generate-dataset-catalog.ts`); the base URL
 * follows the Supabase Storage public bucket `bible-datasets`.
 */

import {
  LocalBibleRepository,
  InMemoryBibleTextSource,
  type ILocalBibleRepository,
  type IBibleTextSource,
  type BibleBookData,
  type BibleTranslationData,
  parseTranslationData,
} from '@/domains/bible/repository-local';
import { BibleJsonFileSource } from '@/infrastructure/bible/bible-json-source';
import {
  createBibleDatasetCache,
  type IBibleDatasetCache,
} from '@/infrastructure/bible/bible-dataset-cache';

// Static catalog of the remote datasets (Supabase Storage, public bucket).
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
import datasetCatalogJson from '../../data/bible/dataset-catalog.json';

export interface BibleDatasetCatalogEntry {
  id: string;
  checksum: string;
  sizeBytes: number;
  builtAt: string;
}

/** The static catalogue of downloadable datasets. */
export const BIBLE_DATASET_CATALOG: BibleDatasetCatalogEntry[] =
  datasetCatalogJson as unknown as BibleDatasetCatalogEntry[];

/** Find the catalogue entry for a translation id, or null. */
export function findRemoteDatasetEntry(
  translationId: string,
): BibleDatasetCatalogEntry | null {
  return BIBLE_DATASET_CATALOG.find((e) => e.id === translationId) ?? null;
}

/**
 * Base URL for the public dataset bucket. Overridable via
 * `VITE_SUPABASE_URL` (the app's Supabase project).
 */
export function datasetBaseUrl(): string {
  const env = (import.meta as unknown as { env?: Record<string, string> }).env;
  const supabaseUrl = env?.VITE_SUPABASE_URL ?? 'https://dspqvyesfngxuwqhceog.supabase.co';
  return `${supabaseUrl.replace(/\/$/, '')}/storage/v1/object/public/bible-datasets`;
}

type LoadResult = BibleBookData[] | null;

const repo: ILocalBibleRepository = new LocalBibleRepository(new BibleJsonFileSource());
let cache: IBibleDatasetCache | null = null;

function peekCache(): IBibleDatasetCache {
  if (!cache) cache = createBibleDatasetCache();
  return cache;
}

/** Load a translation from the local dataset cache only; null on miss. */
async function peekLocal(
  translationId: string,
  checksum: string,
): Promise<BibleTranslationData | null> {
  const entry = findRemoteDatasetEntry(translationId);
  const expected = entry?.checksum ?? checksum;
  const cached = await peekCache().get(translationId, expected);
  if (!cached) return null;
  try {
    return parseTranslationData(JSON.parse(cached.text));
  } catch {
    return null;
  }
}

/** Load (once per session) the book corpus for a translation; null when unavailable. */
export async function loadTranslationBooks(
  translationId: string = 'lsg',
): Promise<LoadResult> {
  // 1. Bundled local dataset (lsg, ostervald, …).
  try {
    return await repo.getBooks(translationId);
  } catch {
    // not bundled — fall through to the download cache.
  }

  // 2. Download-on-demand cache.
  const entry = findRemoteDatasetEntry(translationId);
  if (entry) {
    const data = await peekLocal(translationId, entry.checksum);
    if (data) return data.books;
  }

  // 3. Unavailable — caller may trigger an explicit download.
  return null;
}

/**
 * Download a remote dataset, cache it locally, and return its books.
 *
 * - Skips the network entirely when the cache already holds the expected
 *   checksum (instant second load, fully offline).
 * - Stale cache (checksum changed on the server) is re-downloaded.
 * - `onProgress` reports 0 → 100; intermediate granularity would need a
 *   streaming reader and is not worth it for ~7 MB payloads.
 */
export async function downloadAndLoadTranslationBooks(
  translationId: string,
  onProgress?: (percent: number) => void,
  options: { fetchImpl?: typeof fetch; cacheOverride?: IBibleDatasetCache } = {},
): Promise<BibleBookData[]> {
  const entry = findRemoteDatasetEntry(translationId);
  if (!entry) {
    throw new Error(`No remote dataset registered for translation "${translationId}"`);
  }
  if (!/^[a-z0-9_-]+$/.test(translationId)) {
    throw new Error(`Invalid translation id "${translationId}"`);
  }

  // Cache hit with matching checksum → no download.
  const peek = options.cacheOverride ?? peekCache();
  const cached = await peek.get(translationId, entry.checksum);
  if (cached) {
    return parseTranslationData(JSON.parse(cached.text)).books;
  }

  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  const url = `${datasetBaseUrl()}/${translationId}.json`;
  onProgress?.(0);

  const res = await fetchImpl(url);
  if (!res.ok) {
    throw new Error(`Failed to download Bible dataset "${translationId}" (HTTP ${res.status})`);
  }

  const text = await res.text();
  onProgress?.(100);

  await peek.set({
    id: translationId,
    checksum: entry.checksum,
    text,
    downloadedAt: Date.now(),
  });

  // The INSERT OR REPLACE above supersedes any stale checksum copy.
  const data = parseTranslationData(JSON.parse(text));
  return data.books;
}

// Re-exports for tests that want to build a local source directly.
export { InMemoryBibleTextSource };
