/**
 * BibleTextService — on-demand multi-translation loader.
 *
 * Resolution order for `loadTranslationBooks(id)`:
 *   1. Bundled/local dataset (`LocalBibleRepository` over the bundled JSON).
 *   2. Download-on-demand cache (`bible-dataset-cache`) — only hits when the
 *      checksum still matches the catalogued one.
 *   3. null — the dataset is not available locally; call
 *      `downloadAndLoadTranslationBooks` to fetch it explicitly.
 *
 * The catalogue of remote datasets is the static `data/bible/dataset-catalog.json`
 * (generated by `scripts/bible/generate-dataset-catalog.ts`); the base URL
 * follows the Supabase Storage public bucket `bible-datasets`.
 */

import {
  LocalBibleRepository,
  InMemoryBibleTextSource,
  type ILocalBibleRepository,
  type IBibleTextSource,
  type BibleBookData,
  type BibleTranslationData,
  parseTranslationData,
  filterCanonicalBooks,
} from '@/domains/bible/repository-local';
import { BibleJsonFileSource } from '@/infrastructure/bible/bible-json-source';
import {
  createBibleDatasetCache,
  type IBibleDatasetCache,
} from '@/infrastructure/bible/bible-dataset-cache';

// Static catalog of the remote datasets (Supabase Storage, public bucket).
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
import datasetCatalogJson from '../../data/bible/dataset-catalog.json';

export interface BibleDatasetCatalogEntry {
  id: string;
  checksum: string;
  sizeBytes: number;
  builtAt: string;
}

/**
 * A catalogued dataset that is not yet built/deployed. `checksum` is the
 * literal string `sha256:pending`; `sizeBytes` and `builtAt` are placeholders.
 * Download-on-demand excludes these from `BIBLE_DATASET_CATALOG`.
 */
export interface PendingDatasetCatalogEntry {
  id: string;
  checksum: string; // 'sha256:pending'
  sizeBytes: number;
  builtAt: string;
  status: 'pending';
}

type RawCatalogEntry = BibleDatasetCatalogEntry | PendingDatasetCatalogEntry;

function isBuilt(entry: RawCatalogEntry): entry is BibleDatasetCatalogEntry {
  return !/^sha256:pending$/.test(entry.checksum);
}

/**
 * The static catalogue of **deployable** datasets. Pending stubs
 * (`sha256:pending`) are excluded — they represent catalogued-but-not-yet-
 * built datasets (e.g. `de-tkw`, `pt-brbsl`) that should not be listed as
 * downloadable until `npm run bible:build` + `bible:deploy` complete.
 */
export const BIBLE_DATASET_CATALOG: BibleDatasetCatalogEntry[] =
  ((datasetCatalogJson as unknown as RawCatalogEntry[]).filter(isBuilt));

/** Find the catalogue entry for a translation id, or null. */
export function findRemoteDatasetEntry(
  translationId: string,
): BibleDatasetCatalogEntry | null {
  return BIBLE_DATASET_CATALOG.find((e) => e.id === translationId) ?? null;
}

/**
 * Base URL for the public dataset bucket. Overridable via
 * `VITE_SUPABASE_URL` (the app's Supabase project).
 */
export function datasetBaseUrl(): string {
  const env = (import.meta as unknown as { env?: Record<string, string> }).env;
  const supabaseUrl = env?.VITE_SUPABASE_URL ?? 'https://dspqvyesfngxuwqhceog.supabase.co';
  return `${supabaseUrl.replace(/\/$/, '')}/storage/v1/object/public/bible-datasets`;
}

type LoadResult = BibleBookData[] | null;

const repo: ILocalBibleRepository = new LocalBibleRepository(new BibleJsonFileSource());
let cache: IBibleDatasetCache | null = null;

/** Per-session in-memory mirror of the dataset cache (dev-fast, quota-free). */
const memoryCache = new Map<string, import('@/infrastructure/bible/bible-dataset-cache').CachedBibleDataset>();

function peekCache(): IBibleDatasetCache {
  if (!cache) {
    const base = createBibleDatasetCache();
    cache = {
      get: async (id, checksum) => {
        const mem = memoryCache.get(id);
        if (mem && mem.checksum === checksum) return mem;
        return base.get(id, checksum);
      },
      set: async (dataset) => {
        memoryCache.set(dataset.id, dataset);
        try {
          await base.set(dataset);
        } catch {
          // Quota / no-DB failure: the in-memory mirror already serves this
          // session; persisting is best-effort.
        }
      },
    };
  }
  return cache;
}

function applyCanon(
  books: BibleTranslationData['books'],
): BibleTranslationData['books'] {
  return filterCanonicalBooks(books as unknown as BibleBookData[]) as unknown as BibleTranslationData['books'];
}

/** Load a translation from the local dataset cache only; null on miss. */
async function peekLocal(
  translationId: string,
  checksum: string,
): Promise<BibleTranslationData | null> {
  const entry = findRemoteDatasetEntry(translationId);
  const expected = entry?.checksum ?? checksum;
  const cached = await peekCache().get(translationId, expected);
  if (!cached) return null;
  try {
    // Canon is the source of truth: trim any apocryphal/intro book slots
    // before the data reaches the UI (`parseTranslationData` already
    // filters, re-applying here covers caches written before that fix).
    const data = parseTranslationData(JSON.parse(cached.text));
    data.books = applyCanon(data.books);
    return data;
  } catch {
    return null;
  }
}

/**
 * Load the full dataset for a translation; null when unavailable.
 *
 * Resolution order (first source that has the data wins):
 *   1. Bundled local dataset (`public/data/bible/<id>.json`, copied by
 *      `scripts/copy-bible-bundled.mjs` at build time — `lsg.json` ships
 *      by default). Works in dev AND in the production / Capacitor WebView,
 *      fully offline, so the default translation renders immediately.
 *   2. Download-on-demand cache (only for the 56 remote-only translations).
 *   3. null — the dataset is not available locally; the caller may trigger
 *      an explicit download from the Supabase bucket.
 *
 * In dev the bundled default is the source of truth; the Supabase bucket is
 * only the fallback for the non-bundled translations, so "la Bible" never
 * depends on the network to display the default translation.
 */
export async function loadTranslationData(
  translationId: string = 'lsg',
): Promise<BibleTranslationData | null> {
  const entry = findRemoteDatasetEntry(translationId);

  // 1. Bundled local dataset (the `lsg` default ships in the build; every
  //    other id 404s here on purpose and falls through to the cache).
  try {
    const books = await repo.getBooks(translationId);
    return {
      id: translationId,
      language: 'fr',
      name: translationId,
      // The canonical 66-book structure (Zod tuple); the repository
      // returns the same canon, cast for the fixed shape.
      books: books as unknown as BibleTranslationData['books'],
    };
  } catch {
    // not bundled — fall through to the download cache.
  }

  // 2. Download-on-demand cache (the non-bundled translations).
  if (entry) {
    const data = await peekLocal(translationId, entry.checksum);
    if (data) return data;
  }

  // 3. Unavailable — caller may trigger an explicit download.
  return null;
}

/** Load (once per session) the book corpus for a translation; null when unavailable. */
export async function loadTranslationBooks(
  translationId: string = 'lsg',
): Promise<LoadResult> {
  const data = await loadTranslationData(translationId);
  return data ? data.books : null;
}

/**
 * Download a remote dataset, cache it locally, and return its books.
 *
 * - Skips the network entirely when the cache already holds the expected
 *   checksum (instant second load, fully offline).
 * - Stale cache (checksum changed on the server) is re-downloaded.
 * - `onProgress(percent, receivedBytes)` reports real progress by streaming
 *   the response body chunk by chunk, using the catalogued `sizeBytes` as
 *   the denominator (graceful fallback when unknown).
 * - Pass `options.signal` to abort an in-flight download.
 */
export async function downloadAndLoadTranslationData(
  translationId: string,
  onProgress?: (percent: number, receivedBytes: number) => void,
  options: {
    fetchImpl?: typeof fetch;
    cacheOverride?: IBibleDatasetCache;
    signal?: AbortSignal;
  } = {},
): Promise<BibleTranslationData> {
  const entry = findRemoteDatasetEntry(translationId);
  if (!entry) {
    throw new Error(`No remote dataset registered for translation "${translationId}"`);
  }
  if (!/^[a-z0-9_-]+$/.test(translationId)) {
    throw new Error(`Invalid translation id "${translationId}"`);
  }

  // Cache hit with matching checksum → no download.
  const peek = options.cacheOverride ?? peekCache();
  const cached = await peek.get(translationId, entry.checksum);
  if (cached) {
    onProgress?.(100, cached.text.length);
    const data = parseTranslationData(JSON.parse(cached.text));
    data.books = applyCanon(data.books);
    return data;
  }

  if (options.signal?.aborted) {
    throw new DOMException('Download aborted', 'AbortError');
  }

  // `fetch` must keep its global receiver (detached calls throw
  // "Illegal invocation" in WebKit).
  const fetchImpl = options.fetchImpl ?? globalThis.fetch.bind(globalThis);
  const url = `${datasetBaseUrl()}/${translationId}.json`;
  onProgress?.(0, 0);

  const res = await fetchImpl(url, { signal: options.signal });
  if (!res.ok) {
    throw new Error(`Failed to download Bible dataset "${translationId}" (HTTP ${res.status})`);
  }

  const totalBytes = entry.sizeBytes;

  // Stream the body so progress is real (not a 0→100 jump).
  if (res.body && totalBytes > 0) {
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let received = 0;
    let buf = '';
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      received += value.byteLength;
      buf += decoder.decode(value, { stream: true });
      onProgress?.(Math.min(99, Math.round((received / totalBytes) * 100)), received);
    }
    buf += decoder.decode();
    onProgress?.(100, received);
    await peek.set({
      id: translationId,
      checksum: entry.checksum,
      text: buf,
      downloadedAt: Date.now(),
    });
    // The INSERT OR REPLACE above supersedes any stale checksum copy.
    const data = parseTranslationData(JSON.parse(buf));
    data.books = applyCanon(data.books);
    return data;
  }

  // Fallback: no readable body or unknown size — one-shot read.
  const text = await res.text();
  onProgress?.(100, text.length);
  await peek.set({
    id: translationId,
    checksum: entry.checksum,
    text,
    downloadedAt: Date.now(),
  });

  // The INSERT OR REPLACE above supersedes any stale checksum copy.
  const data = parseTranslationData(JSON.parse(text));
  data.books = applyCanon(data.books);
  return data;
}

export async function downloadAndLoadTranslationBooks(
  translationId: string,
  onProgress?: (percent: number, receivedBytes: number) => void,
  options: {
    fetchImpl?: typeof fetch;
    cacheOverride?: IBibleDatasetCache;
    signal?: AbortSignal;
  } = {},
): Promise<BibleBookData[]> {
  return (await downloadAndLoadTranslationData(translationId, onProgress, options)).books;
}

/**
 * Resolve a ready-to-use `IBibleTextSource` for a translation, following the
 * full chain: bundled → download cache → Supabase bucket download.
 *
 * Use anywhere a source/repository is required (e.g. the memorization
 * session engine) instead of building a `BibleJsonFileSource` directly —
 * that raw file source 404/SPA-falls-back in dev and breaks with
 * "Unexpected token '<'" when parsing index.html as JSON.
 */
export async function resolveBibleTextSource(
  translationId: string,
  onProgress?: (percent: number) => void,
): Promise<IBibleTextSource> {
  let data = await loadTranslationData(translationId);
  if (!data) {
    data = await downloadAndLoadTranslationData(translationId, onProgress);
  }
  return new InMemoryBibleTextSource({ [translationId]: data });
}

// Re-exports for tests that want to build a local source directly.
export { InMemoryBibleTextSource };

// =====================================================================
// Translation stats (chapter / verse counts) — cached in localStorage
// =====================================================================

export interface TranslationStats {
  chapters: number;
  verses: number;
  /** Year found in the dataset, when present. */
  year?: number;
}

/**
 * localStorage cache so the "Détail" UI reopens instantly without
 * re-scanning ~30 MB of JSON: `{ [id]: { stats, at } }` keyed by
 * translation id, expired after 24 h.
 */
const STATS_CACHE_KEY = 'versyflow-bible-stats-v1';
const STATS_CACHE_TTL_MS = 24 * 60 * 60 * 1000;

type StatsCache = Record<string, { stats: TranslationStats; at: number }>;

function readStatsCache(): StatsCache {
  try {
    const raw = globalThis.localStorage?.getItem(STATS_CACHE_KEY);
    const parsed: unknown = raw ? JSON.parse(raw) : {};
    // A stored payload that is not a plain object (e.g. the literal `null`
    // string, or a stray array/primitive) is treated as "no cache" — the
    // caller indexes the result, so it must never be `null`/`undefined`.
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed)
      ? (parsed as StatsCache)
      : {};
  } catch {
    return {};
  }
}

function writeStatsCache(entry: Record<string, { stats: TranslationStats; at: number }>) {
  try {
    globalThis.localStorage?.setItem(STATS_CACHE_KEY, JSON.stringify(entry));
  } catch {
    /* localStorage unavailable / full — stats stay in-memory for the session */
  }
}

function computeStats(data: BibleTranslationData): TranslationStats {
  let chapters = 0;
  let verses = 0;
  for (const book of data.books) {
    chapters += book.chapters.length;
    for (const chapter of book.chapters) {
      verses += chapter.verses.length;
    }
  }
  return { chapters, verses, year: data.year };
}

/**
 * Chapter + verse counts for a translation, cached 24 h in localStorage.
 *
 * Resolution order per id (first available source wins):
 *   1. in-memory stats cache (same-session fast path)
 *   2. localStorage 24 h cache
 *   3. `loadTranslationData` (bundled JSON in prod / download cache)
 *   4. explicit download from the Supabase bucket (dev, or when not cached)
 *
 * Returns `null` when the id has no dataset anywhere (unknown translation).
 */
const statsMemoryCache = new Map<string, TranslationStats>();

export async function getTranslationStats(
  translationId: string,
): Promise<TranslationStats | null> {
  const mem = statsMemoryCache.get(translationId);
  if (mem) return mem;

  const disk = readStatsCache();
  const diskEntry = disk[translationId];
  if (diskEntry && Date.now() - diskEntry.at < STATS_CACHE_TTL_MS) {
    statsMemoryCache.set(translationId, diskEntry.stats);
    return diskEntry.stats;
  }

  let data = await loadTranslationData(translationId);
  if (!data) {
    // Not resolvable locally — download it explicitly (the canonical dev path).
    try {
      data = await downloadAndLoadTranslationData(translationId);
    } catch {
      return null;
    }
  }
  const stats = computeStats(data);
  statsMemoryCache.set(translationId, stats);
  const next = { ...disk, [translationId]: { stats, at: Date.now() } };
  writeStatsCache(next);
  return stats;
}
