/**
 * BibleTextService — on-demand multi-translation loader.
 *
 * Resolution order for `loadTranslationBooks(id)`:
 *   1. Bundled/local dataset (`LocalBibleRepository` over the bundled JSON).
 *   2. Download-on-demand cache (`bible-dataset-cache`) — only hits when the
 *      checksum still matches the catalogued one.
 *   3. null — the dataset is not available locally; call
 *      `downloadAndLoadTranslationBooks` to fetch it explicitly.
 *
 * The catalogue of remote datasets is the static `data/bible/dataset-catalog.json`
 * (generated by `scripts/bible/generate-dataset-catalog.ts`); the base URL
 * follows the Supabase Storage public bucket `bible-datasets`.
 */

import {
  LocalBibleRepository,
  InMemoryBibleTextSource,
  type ILocalBibleRepository,
  type IBibleTextSource,
  type BibleBookData,
  type BibleTranslationData,
  parseTranslationData,
} from '@/domains/bible/repository-local';
import { BibleJsonFileSource } from '@/infrastructure/bible/bible-json-source';
import {
  createBibleDatasetCache,
  type IBibleDatasetCache,
} from '@/infrastructure/bible/bible-dataset-cache';

// Static catalog of the remote datasets (Supabase Storage, public bucket).
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
import datasetCatalogJson from '../../data/bible/dataset-catalog.json';

export interface BibleDatasetCatalogEntry {
  id: string;
  checksum: string;
  sizeBytes: number;
  builtAt: string;
}

/** The static catalogue of downloadable datasets. */
export const BIBLE_DATASET_CATALOG: BibleDatasetCatalogEntry[] =
  datasetCatalogJson as unknown as BibleDatasetCatalogEntry[];

/** Find the catalogue entry for a translation id, or null. */
export function findRemoteDatasetEntry(
  translationId: string,
): BibleDatasetCatalogEntry | null {
  return BIBLE_DATASET_CATALOG.find((e) => e.id === translationId) ?? null;
}

/**
 * Base URL for the public dataset bucket. Overridable via
 * `VITE_SUPABASE_URL` (the app's Supabase project).
 */
export function datasetBaseUrl(): string {
  const env = (import.meta as unknown as { env?: Record<string, string> }).env;
  const supabaseUrl = env?.VITE_SUPABASE_URL ?? 'https://dspqvyesfngxuwqhceog.supabase.co';
  return `${supabaseUrl.replace(/\/$/, '')}/storage/v1/object/public/bible-datasets`;
}

type LoadResult = BibleBookData[] | null;

const repo: ILocalBibleRepository = new LocalBibleRepository(new BibleJsonFileSource());
let cache: IBibleDatasetCache | null = null;

/**
 * In dev the app is expected to use the REAL Supabase Storage bucket as its
 * source of truth (not the bundled `data/bible/*.json` files, which are
 * treated as mock/offline fixtures). `import.meta.env.DEV` is true under
 * Vite's dev server.
 */
function preferRemoteSource(): boolean {
  const env = (import.meta as unknown as { env?: Record<string, unknown> }).env;
  return env?.DEV === true;
}

/** Per-session in-memory mirror of the dataset cache (dev-fast, quota-free). */
const memoryCache = new Map<string, import('@/infrastructure/bible/bible-dataset-cache').CachedBibleDataset>();

function peekCache(): IBibleDatasetCache {
  if (!cache) {
    const base = createBibleDatasetCache();
    cache = {
      get: async (id, checksum) => {
        const mem = memoryCache.get(id);
        if (mem && mem.checksum === checksum) return mem;
        return base.get(id, checksum);
      },
      set: async (dataset) => {
        memoryCache.set(dataset.id, dataset);
        try {
          await base.set(dataset);
        } catch {
          // Quota / no-DB failure: the in-memory mirror already serves this
          // session; persisting is best-effort.
        }
      },
    };
  }
  return cache;
}

/** Load a translation from the local dataset cache only; null on miss. */
async function peekLocal(
  translationId: string,
  checksum: string,
): Promise<BibleTranslationData | null> {
  const entry = findRemoteDatasetEntry(translationId);
  const expected = entry?.checksum ?? checksum;
  const cached = await peekCache().get(translationId, expected);
  if (!cached) return null;
  try {
    return parseTranslationData(JSON.parse(cached.text));
  } catch {
    return null;
  }
}

/** Load the full dataset for a translation; null when unavailable. */
export async function loadTranslationData(
  translationId: string = 'lsg',
): Promise<BibleTranslationData | null> {
  const entry = findRemoteDatasetEntry(translationId);

  // Dev: the real Supabase bucket is the source of truth. Serve from the
  // download cache when present; otherwise report "unavailable" so the caller
  // triggers a fresh fetch from the bucket (never reads the local mock files).
  if (preferRemoteSource() && entry) {
    return peekLocal(translationId, entry.checksum);
  }

  // 1. Bundled local dataset (production / offline).
  try {
    return await repo.getBooks(translationId).then((books) => {
      // Rebuild the minimal valid dataset shape from the books payload.
      return {
        id: translationId,
        language: 'fr',
        name: translationId,
        // The canonical 66-book structure (Zod tuple); the repository
        // returns the same canon, cast for the fixed shape.
        books: books as unknown as BibleTranslationData['books'],
      };
    });
  } catch {
    // not bundled — fall through to the download cache.
  }

  // 2. Download-on-demand cache.
  if (entry) {
    const data = await peekLocal(translationId, entry.checksum);
    if (data) return data;
  }

  // 3. Unavailable — caller may trigger an explicit download.
  return null;
}

/** Load (once per session) the book corpus for a translation; null when unavailable. */
export async function loadTranslationBooks(
  translationId: string = 'lsg',
): Promise<LoadResult> {
  const data = await loadTranslationData(translationId);
  return data ? data.books : null;
}

/**
 * Download a remote dataset, cache it locally, and return its books.
 *
 * - Skips the network entirely when the cache already holds the expected
 *   checksum (instant second load, fully offline).
 * - Stale cache (checksum changed on the server) is re-downloaded.
 * - `onProgress(percent, receivedBytes)` reports real progress by streaming
 *   the response body chunk by chunk, using the catalogued `sizeBytes` as
 *   the denominator (graceful fallback when unknown).
 * - Pass `options.signal` to abort an in-flight download.
 */
export async function downloadAndLoadTranslationData(
  translationId: string,
  onProgress?: (percent: number, receivedBytes: number) => void,
  options: {
    fetchImpl?: typeof fetch;
    cacheOverride?: IBibleDatasetCache;
    signal?: AbortSignal;
  } = {},
): Promise<BibleTranslationData> {
  const entry = findRemoteDatasetEntry(translationId);
  if (!entry) {
    throw new Error(`No remote dataset registered for translation "${translationId}"`);
  }
  if (!/^[a-z0-9_-]+$/.test(translationId)) {
    throw new Error(`Invalid translation id "${translationId}"`);
  }

  // Cache hit with matching checksum → no download.
  const peek = options.cacheOverride ?? peekCache();
  const cached = await peek.get(translationId, entry.checksum);
  if (cached) {
    onProgress?.(100, cached.text.length);
    return parseTranslationData(JSON.parse(cached.text));
  }

  if (options.signal?.aborted) {
    throw new DOMException('Download aborted', 'AbortError');
  }

  // `fetch` must keep its global receiver (detached calls throw
  // "Illegal invocation" in WebKit).
  const fetchImpl = options.fetchImpl ?? globalThis.fetch.bind(globalThis);
  const url = `${datasetBaseUrl()}/${translationId}.json`;
  onProgress?.(0, 0);

  const res = await fetchImpl(url, { signal: options.signal });
  if (!res.ok) {
    throw new Error(`Failed to download Bible dataset "${translationId}" (HTTP ${res.status})`);
  }

  const totalBytes = entry.sizeBytes;

  // Stream the body so progress is real (not a 0→100 jump).
  if (res.body && totalBytes > 0) {
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let received = 0;
    let buf = '';
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      received += value.byteLength;
      buf += decoder.decode(value, { stream: true });
      onProgress?.(Math.min(99, Math.round((received / totalBytes) * 100)), received);
    }
    buf += decoder.decode();
    onProgress?.(100, received);
    await peek.set({
      id: translationId,
      checksum: entry.checksum,
      text: buf,
      downloadedAt: Date.now(),
    });
    // The INSERT OR REPLACE above supersedes any stale checksum copy.
    return parseTranslationData(JSON.parse(buf));
  }

  // Fallback: no readable body or unknown size — one-shot read.
  const text = await res.text();
  onProgress?.(100, text.length);
  await peek.set({
    id: translationId,
    checksum: entry.checksum,
    text,
    downloadedAt: Date.now(),
  });

  // The INSERT OR REPLACE above supersedes any stale checksum copy.
  return parseTranslationData(JSON.parse(text));
}

export async function downloadAndLoadTranslationBooks(
  translationId: string,
  onProgress?: (percent: number, receivedBytes: number) => void,
  options: {
    fetchImpl?: typeof fetch;
    cacheOverride?: IBibleDatasetCache;
    signal?: AbortSignal;
  } = {},
): Promise<BibleBookData[]> {
  return (await downloadAndLoadTranslationData(translationId, onProgress, options)).books;
}

/**
 * Resolve a ready-to-use `IBibleTextSource` for a translation, following the
 * full chain: bundled → download cache → Supabase bucket download.
 *
 * Use anywhere a source/repository is required (e.g. the memorization
 * session engine) instead of building a `BibleJsonFileSource` directly —
 * that raw file source 404/SPA-falls-back in dev and breaks with
 * "Unexpected token '<'" when parsing index.html as JSON.
 */
export async function resolveBibleTextSource(
  translationId: string,
  onProgress?: (percent: number) => void,
): Promise<IBibleTextSource> {
  let data = await loadTranslationData(translationId);
  if (!data) {
    data = await downloadAndLoadTranslationData(translationId, onProgress);
  }
  return new InMemoryBibleTextSource({ [translationId]: data });
}

// Re-exports for tests that want to build a local source directly.
export { InMemoryBibleTextSource };
