/**
 * Color theme image catalog — 10 categories × 10 themes.
 *
 * Each theme is a flat 2D monochrome illustration (single core color on
 * white) generated by `scripts/generate-themes.mjs` and stored under
 * `public/themes/{category}/{id}-{portrait|landscape}.png`:
 *  - `-portrait.png` (1024×1536) = the applied full-screen theme
 *  - `-landscape.png` (1536×1024) = the thumbnail used in the picker
 *
 * The catalog mirrors the definitions in that script (category, name,
 * motif, color). The theme id is the unique key persisted in the
 * appearance store (`accent` = id when the user picked an image theme,
 * a preset key when they picked a plain accent color).
 */

export interface ThemeCatalogEntry {
  id: string;
  category: string;
  name: string;
  color: string;
  motif: string;
}

export interface ThemeCategory {
  id: string;
  name: string;
  themes: Omit<ThemeCatalogEntry, 'category'>[];
}

export const THEME_CATEGORIES: ThemeCategory[] = [
  {
    id: 'esprit',
    name: 'Esprit',
    themes: [
      { id: 'esprit-pentecote', name: 'Pentecôte', color: '#C0392B', motif: 'a single descending flame / tongue of fire above a small cluster of heads' },
      { id: 'esprit-feu', name: 'Feu du Saint-Esprit', color: '#E74C3C', motif: 'a single flame rising from a small open book' },
      { id: 'esprit-zel', name: 'Zèle', color: '#F39C12', motif: 'a single spark with radiating lines' },
      { id: 'esprit-olivier', name: 'Rameau d’olivier', color: '#27AE60', motif: 'a single olive branch with leaves' },
      { id: 'esprit-dove', name: 'Colombe', color: '#3498DB', motif: 'a single dove in flight' },
      { id: 'esprit-eau', name: 'Eau vive', color: '#1ABC9C', motif: 'a single water drop with ripple rings' },
      { id: 'esprit-semin', name: 'Sémin (vent)', color: '#8E44AD', motif: 'three curved wind lines with a small leaf' },
      { id: 'esprit-nouvel', name: 'Vie nouvelle', color: '#2ECC71', motif: 'a single sprout with two leaves' },
      { id: 'esprit-tete', name: 'Lumière de l’esprit', color: '#F1C40F', motif: 'a single glowing bulb with rays' },
      { id: 'esprit-rain', name: 'Pluie d’esprit', color: '#5DADE2', motif: 'three falling drops with small ripples' },
    ],
  },
  {
    id: 'evenements',
    name: 'Événements',
    themes: [
      { id: 'ev-pasque', name: 'Pâque', color: '#7D3C98', motif: 'a single lamb silhouette' },
      { id: 'ev-noel', name: 'Noël', color: '#1E8449', motif: 'a single Christmas tree with a small star on top' },
      { id: 'ev-epee', name: 'Épiphanie', color: '#F4D03F', motif: 'a single star with rays on small hills' },
      { id: 'ev-temple', name: 'Temple', color: '#B03A2E', motif: 'a single temple with columns and a small roof' },
      { id: 'ev-lent', name: 'Carême', color: '#566573', motif: 'a single hourglass' },
      { id: 'ev-ascension', name: 'Ascension', color: '#2C3E50', motif: 'a single cloud with a rising arrow' },
      { id: 'ev-toussaint', name: 'Toussaint', color: '#154360', motif: 'a single candle flame' },
      { id: 'ev-resurrection', name: 'Résurrection', color: '#A93226', motif: 'an open empty tomb (stone rolled aside)' },
      { id: 'ev-bapteme', name: 'Baptême', color: '#148F77', motif: 'a single water drop over an open scroll' },
      { id: 'ev-harvest', name: 'Moisson', color: '#B7950B', motif: 'a single wheat stalk with grains' },
    ],
  },
  {
    id: 'villes',
    name: 'Villes',
    themes: [
      { id: 'villes-paris', name: 'Paris', color: '#34495E', motif: 'the Eiffel Tower, flat 2D single silhouette' },
      { id: 'villes-berlin', name: 'Berlin', color: '#7F8C8D', motif: 'the Brandenburg Gate, flat 2D single silhouette' },
      { id: 'villes-caire', name: 'Le Caire', color: '#B7950B', motif: 'a single pyramid with a smaller one behind' },
      { id: 'villes-pekin', name: 'Pékin', color: '#922B21', motif: 'the Great Wall arching over hills' },
      { id: 'villes-madrid', name: 'Madrid', color: '#CA6F1E', motif: 'a single bull silhouette' },
      { id: 'villes-lisbonne', name: 'Lisbonne', color: '#1F618D', motif: 'a single bridge over wavy water' },
      { id: 'villes-jakarta', name: 'Jakarta', color: '#148F77', motif: 'a single mosque with a crescent dome' },
      { id: 'villes-delhi', name: 'Delhi', color: '#B03A2E', motif: 'the Lotus Temple, flat 2D single silhouette' },
      { id: 'villes-istanbul', name: 'Istanbul', color: '#5B2C6F', motif: 'the Blue Mosque with minarets, flat 2D single silhouette' },
      { id: 'villes-stpetersbourg', name: 'St Pétersbourg', color: '#1A5276', motif: 'a single church with an onion dome and cross' },
    ],
  },
  {
    id: 'natures',
    name: 'Nature',
    themes: [
      { id: 'nat-trees', name: 'Forêt', color: '#1E8449', motif: 'three pine trees of varying heights' },
      { id: 'nat-mont', name: 'Montagnes', color: '#4A235A', motif: 'a single mountain peak with a small snow cap' },
      { id: 'nat-cactus', name: 'Désert', color: '#CA6F1E', motif: 'a single cactus with a small sun' },
      { id: 'nat-fleurs', name: 'Fleurs', color: '#C2185B', motif: 'three flowers with stems and leaves' },
      { id: 'nat-feuille', name: 'Feuillage', color: '#27AE60', motif: 'a single large leaf with veins' },
      { id: 'nat-paon', name: 'Oiseau', color: '#1565C0', motif: 'a single bird perched on a branch' },
      { id: 'nat-lune', name: 'Lune', color: '#1B4F72', motif: 'a crescent moon with three small stars' },
      { id: 'nat-sun', name: 'Soleil', color: '#F39C12', motif: 'a single sun with rays above a small hill' },
      { id: 'nat-ocean', name: 'Océan', color: '#0E6655', motif: 'three wavy lines and a small anchor' },
      { id: 'nat-pluie', name: 'Pluie', color: '#21618C', motif: 'a single cloud with three drops' },
    ],
  },
  {
    id: 'sagesse',
    name: 'Sagesse',
    themes: [
      { id: 'sag-livre', name: 'Livre', color: '#6E2C00', motif: 'an open book with two pages' },
      { id: 'sag-plume', name: 'Plume', color: '#283747', motif: 'a single feather quill' },
      { id: 'sag-lam', name: 'Lamplume', color: '#B9770E', motif: 'a single oil lamp with a flame' },
      { id: 'sag-perle', name: 'Perle', color: '#A569BD', motif: 'a single pearl in an open shell' },
      { id: 'sag-miroir', name: 'Miroir', color: '#566573', motif: 'a round mirror on a stand' },
      { id: 'sag-tri', name: 'Triangle', color: '#1F618D', motif: 'a single equilateral triangle with inner lines' },
      { id: 'sag-horloger', name: 'Boussole', color: '#117864', motif: 'a single compass rose' },
      { id: 'sag-geometrie', name: 'Geométrie', color: '#4A235A', motif: 'overlapping circles and squares' },
      { id: 'sag-colonne', name: 'Colonne', color: '#7B241C', motif: 'a single classical column' },
      { id: 'sag-sceau', name: 'Sceau', color: '#B03A2E', motif: 'a single wax seal with a ribbon' },
    ],
  },
  {
    id: 'fraternite',
    name: 'Fraternité',
    themes: [
      { id: 'frat-pains', name: 'Pain partagé', color: '#B9770E', motif: 'two loaves of bread on a plate' },
      { id: 'frat-table', name: 'Table commune', color: '#6E2C00', motif: 'a single round table with a cup and plate' },
      { id: 'frat-mains', name: 'Mains jointes', color: '#A04000', motif: 'two hands clasped together' },
      { id: 'frat-cord', name: 'Cordes liées', color: '#1F618D', motif: 'two interlocking rings' },
      { id: 'frat-grenade', name: 'Cèdre', color: '#1E8449', motif: 'a single cedar tree' },
      { id: 'frat-lantern', name: 'Lanterne', color: '#B9770E', motif: 'a single lantern with a flame' },
      { id: 'frat-rainbow', name: 'Arc-en-ciel', color: '#C2185B', motif: 'three curved arcs over a small house' },
      { id: 'frat-tour', name: 'Tour', color: '#283747', motif: 'a single tower with a small flag' },
      { id: 'frat-oiseaux', name: 'Oiseaux', color: '#1565C0', motif: 'three birds in flight' },
      { id: 'frat-couron', name: 'Couronne', color: '#B03A2E', motif: 'a single crown' },
    ],
  },
  {
    id: 'lumieres',
    name: 'Lumières',
    themes: [
      { id: 'lum-etoile', name: 'Étoile', color: '#F1C40F', motif: 'a five-pointed star' },
      { id: 'lum-lanter', name: 'Lanterne', color: '#E67E22', motif: 'a single lantern hanging from a hook' },
      { id: 'lum-chand', name: 'Chandelle', color: '#F9E79F', motif: 'a single lit candle' },
      { id: 'lum-bougie', name: 'Bougie', color: '#F4D03F', motif: 'a small candle in a holder' },
      { id: 'lum-lune', name: 'Lune', color: '#1B4F72', motif: 'a crescent moon' },
      { id: 'lum-sunrise', name: 'Lever de soleil', color: '#CA6F1E', motif: 'a half sun over wavy water' },
      { id: 'lum-lamp', name: 'Lampe', color: '#B9770E', motif: 'a single table lamp' },
      { id: 'lum-feu', name: 'Feu de camp', color: '#E74C3C', motif: 'a single flame over three logs' },
      { id: 'lum-phares', name: 'Phare', color: '#1565C0', motif: 'a single lighthouse with a light beam' },
      { id: 'lum-diamant', name: 'Diamant', color: '#A569BD', motif: 'a single cut gemstone' },
    ],
  },
  {
    id: 'saisons',
    name: 'Saisons',
    themes: [
      { id: 'sai-printemps', name: 'Printemps', color: '#27AE60', motif: 'a single cherry blossom branch' },
      { id: 'sai-ete', name: 'Été', color: '#F39C12', motif: 'a single sun with a leaf' },
      { id: 'sai-autome', name: 'Automne', color: '#CA6F1E', motif: 'three falling leaves' },
      { id: 'sai-hiver', name: 'Hiver', color: '#21618C', motif: 'a single snowflake' },
      { id: 'sai-neige', name: 'Neige', color: '#1B4F72', motif: 'three snowflakes of varying size' },
      { id: 'sai-rain', name: 'Pluie', color: '#566573', motif: 'a single cloud with drops' },
      { id: 'sai-fleur', name: 'Fleur', color: '#C2185B', motif: 'a single flower with petals' },
      { id: 'sai-feuille', name: 'Feuille', color: '#1E8449', motif: 'a single maple leaf' },
      { id: 'sai-nuit', name: 'Nuit', color: '#154360', motif: 'a crescent moon with three stars' },
      { id: 'sai-dawn', name: 'Aube', color: '#F4D03F', motif: 'a half sun over hills with rays' },
    ],
  },
  {
    id: 'animaux',
    name: 'Animaux',
    themes: [
      { id: 'ani-belle', name: 'Gazelle', color: '#B9770E', motif: 'a single gazelle silhouette' },
      { id: 'ani-agneau', name: 'Agneau', color: '#6E2C00', motif: 'a single lamb' },
      { id: 'ani-pigeon', name: 'Pigeon', color: '#283747', motif: 'a single pigeon in flight' },
      { id: 'ani-abeille', name: 'Abeille', color: '#F39C12', motif: 'a single bee over a flower' },
      { id: 'ani-colombe', name: 'Colombe', color: '#1565C0', motif: 'a single dove holding an olive branch' },
      { id: 'ani-taupe', name: 'Taupe', color: '#6E2C00', motif: 'a single mole' },
      { id: 'ani-cam', name: 'Chameau', color: '#CA6F1E', motif: 'a single camel' },
      { id: 'ani-pharaon', name: 'Pharaon', color: '#B03A2E', motif: 'a single ankh symbol' },
      { id: 'ani-scorp', name: 'Scorpion', color: '#4A235A', motif: 'a single scorpion' },
      { id: 'ani-aigle', name: 'Aigle', color: '#283747', motif: 'a single eagle with spread wings' },
    ],
  },
  {
    id: 'objets',
    name: 'Objets',
    themes: [
      { id: 'obj-cle', name: 'Clé', color: '#B9770E', motif: 'a single antique key' },
      { id: 'obj-sceau', name: 'Sceau', color: '#B03A2E', motif: 'a single wax seal' },
      { id: 'obj-vase', name: 'Vase', color: '#1F618D', motif: 'a single amphora vase' },
      { id: 'obj-jar', name: 'Jarre', color: '#CA6F1E', motif: 'a single clay jar' },
      { id: 'obj-ankh', name: 'Ankh', color: '#B03A2E', motif: 'a single ankh cross' },
      { id: 'obj-swan', name: 'Cygne', color: '#283747', motif: 'a single swan on water' },
      { id: 'obj-anchor', name: 'Ancre', color: '#1565C0', motif: 'a single anchor' },
      { id: 'obj-veil', name: 'Voile', color: '#A569BD', motif: 'a single veil draping over a face' },
      { id: 'obj-donnee', name: 'Don', color: '#C2185B', motif: 'a single gift box with a ribbon' },
      { id: 'obj-miroir', name: 'Miroir', color: '#566573', motif: 'a single hand mirror' },
    ],
  },
];

/** All themes flattened (100 entries). */
export const ALL_THEMES: ThemeCatalogEntry[] = THEME_CATEGORIES.flatMap((c) =>
  c.themes.map((t) => ({ ...t, category: c.id })),
);

export function findThemeById(id: string | null | undefined): ThemeCatalogEntry | null {
  if (!id) return null;
  return ALL_THEMES.find((t) => t.id === id) ?? null;
}

/**
 * True when the given accent value (from the appearance store) points to an
 * image-based theme (as opposed to a plain color preset like 'magenta').
 */
export function isImageTheme(accent: string | null | undefined): boolean {
  return accent != null && findThemeById(accent) != null;
}

/** Image URLs for the catalog. */
export function themePortraitUrl(id: string): string {
  return `/themes/${id.split('-').slice(0, 2).join('-')}/${id}-portrait.png`;
}
export function themeLandscapeUrl(id: string): string {
  return `/themes/${id.split('-').slice(0, 2).join('-')}/${id}-landscape.png`;
}
