/**
 * I18n Localization — Arabic (RTL)
 */

export const ar = {
  common: { appName: 'VersyFlow', continue: 'متابعة', skip: 'تخطي', back: 'رجوع', done: 'تم', loading: 'جاري التحميل...', error: 'خطأ', cancel: 'إلغاء', confirm: 'تأكيد', delete: 'حذف', search: 'بحث' },
  onboarding: { welcome: 'مرحباً بك في VersyFlow', selectLanguage: 'اختر لغتك', selectTranslation: 'اختر ترجمة الكتاب المقدس', rtlWarning: 'سوف تنتقل الواجهة إلى القراءة من اليمين إلى اليسار', slide1Title: 'اختر ترجمتك', slide1Desc: 'من الترجمات الكتابية المتاحة', slide2Title: 'احفظ بالعلم', slide2Desc: 'خوارزمية FSRS محسّنة بالرست', slide3Title: 'تتبع تقدمك', slide3Desc: 'إحصائيات مفصلة ومتسلسل يومي' },
  home: { greeting: 'مرحباً', reviewDue: '{count} آية{plural} للمراجعة', streak: '{count} يوم{plural} متتالي!', explore: 'استكشف الكتاب المقدس', dailyVerse: 'آية اليوم', noReviews: 'كل شيء محدث! ✓', goodJob: 'عمل ممتاز' },
  bible: { explorer: 'استكشف الكتاب المقدس', book: 'كتاب', chapter: 'فصل', verse: 'آية', memorize: 'احفظ هذه الآية', favorite: 'أضف للمفضلة', search: 'ابحث عن مرجع...', oldTestament: 'العهد القديم', newTestament: 'العهد الجديد', verseCount: '{count} آية{plural}', chapterCount: '{count} فصل{plural}' },
  session: { memorizing: 'الحفظ', allWordsRevealed: 'تم الكشف عن جميع الكلمات', iMemorized: 'لقد حفظتها', needMoreTime: 'أحتاج المزيد من الوقت', tapToReveal: 'انقر للكشف', timeElapsed: 'الوقت: {seconds} ثانية', verseComplete: 'تم حفظ الآية! ✨', nextReview: 'التذكير القادم: بعد {days} يوم{plural}', startingPassage: 'بدء المقطع…', verseReference: 'مرجع الآية', verseOf: 'الآية {current} من {total}', ratingAgain: 'مرة أخرى', ratingHard: 'صعب', ratingGood: 'جيد', ratingEasy: 'سهل', goBack: 'رجوع', proceed: 'متابعة', passageComplete: 'تم إتمام المقطع!', activeSessionTitle: 'جلسة نشطة', saveAndContinue: 'حفظ ومتابعة' },
  family: { invite: 'دعوة', inviteCodeCopied: 'تم نسخ الرمز!', shareTitle: 'مشاركة', generateCode: 'توليد الرمز', join: 'انضم', joinButton: 'انضم إلى العائلة', scanQR: 'امسح رمز QR', or: 'أو', members: 'الأعضاء', noFamily: 'لا توجد عائلة نشطة', roleOwner: 'المالك', inviteMember: 'دعوة عضو', contextFamily: 'عائلة', contextPersonal: 'شخصي', contextMyProfile: 'ملفي', switchContext: 'تبديل السياق', contextPersonalDesc: 'مكاني الخاص', createFamily: 'إنشاء عائلة', selectProfile: 'الملف', selectLearner: 'اختيار', familyMember: 'عضو في العائلة', myProfile: 'ملفي', tapSelect: 'انقر للاختيار' },
  comparison: { analyzing: 'تحليل...', finish: 'إنهاء', substitutions: 'استبدالات', loading: 'جاري التحميل...', title: 'مقارنة الترجمات', available: 'متوفر' },
  review: { todayReviews: 'مراجعات اليوم', overdue: 'متأخر', dueSoon: 'قريباً', totalDue: '{count} للمراجعة', estimatedTime: '~{minutes} دقيقة', startReview: 'ابدأ المراجعة', iRecalled: 'تذكرتها', almost: 'شبه صحيحة', forgot: 'نسيتها', correct: 'صحيحة!', summary: 'ملخص الجلسة', easy: 'سهل', hard: 'صعب', again: 'مرة أخرى', good: 'جيد' },
  progress: { yourProgress: 'تقدمك', versesMemorized: 'آية{plural} محفوظة{plural}', inProgress: 'جارٍ', toReview: 'للمراجعة', streak: 'متسلسل', retention: 'الإبقاء', thisWeek: 'هذا الأسبوع', recentVerses: 'الآيات الأخيرة', needsStrengthening: 'تحتاج تقوية', mastered: 'متقنة', due: 'مستحقة' },
  settings: { settings: 'الإعدادات', uiLanguage: 'لغة الواجهة', bibleTranslation: 'ترجمة الكتاب المقدس', theme: 'المظهر', light: 'فاتح', dark: 'داكن', dataManagement: 'البيانات والتخزين', storageUsed: 'التخزين المستخدم', exportData: 'تصدير البيانات', about: 'حول', version: 'الإصدار', documentation: 'التوثيق', resetProgress: 'إعادة تعيين التقدم', resetConfirmTitle: 'هل أنت متأكد؟', resetConfirmText: 'سيتم حذف جميع آياتك المحفوظة والتاريخ.', typeConfirm: 'اكتب SUPPRIMER للتأكيد' },
  errors: { translationReset: 'تم إعادة تعيين الترجمة إلى LSG', verseNotFound: 'الآية غير متوفرة في هذه الترجمة', wasmFailed: 'محرك المراجعة معطل. تم تفعيل الخوارزمية المبسطة.', databaseCorrupt: 'قاعدة البيانات تالفة. استعادة من النسخ الاحتياطي...', unknownError: 'حدث خطأ غير متوقع' },
} as const;
