/**
 * I18n Localization — German (de)
 */

export const de = {
  common: { appName: 'VersyFlow', continue: 'Weiter', skip: 'Überspringen', back: 'Zurück', done: 'Fertig', loading: 'Laden...', error: 'Fehler', cancel: 'Abbrechen', confirm: 'Bestätigen', delete: 'Löschen', search: 'Suchen' },
  onboarding: { welcome: 'Willkommen bei VersyFlow', selectLanguage: 'Wähle deine Sprache', selectTranslation: 'Wähle deine Bibelübersetzung', rtlWarning: 'Die Oberfläche wechselt zur Rechts-nach-Links-Lesrichtung', slide1Title: 'Wähle deine Übersetzung', slide1Desc: 'Aus verfügbaren Bibelübersetzungen', slide2Title: 'Memorieren mit Wissenschaft', slide2Desc: 'FSRS-Algorithmus optimiert in Rust', slide3Title: 'Verfolge deinen Fortschritt', slide3Desc: 'Detaillierte Statistiken und tägliche Serie' },
  home: { greeting: 'Hallo', reviewDue: '{count} Vers{plural} zum Überprüfen', streak: '{count} Tag{e} Serie!', explore: 'Bibel entdecken', dailyVerse: 'Vers des Tages', noReviews: 'Alles aktualisiert! ✓', goodJob: 'Ausgezeichnete Arbeit' },
  bible: { explorer: 'Bibelerkundung', book: 'Buch', chapter: 'Kapitel', verse: 'Vers', memorize: 'Diesen Vers memorieren', favorite: 'Zu Favoriten', search: 'Referenz suchen...', oldTestament: 'Alter Testament', newTestament: 'Neues Testament', verseCount: '{count} Vers{e}', chapterCount: '{count} Kapitel{e}' },
  session: { memorizing: 'Memorieren', allWordsRevealed: 'Alle Wörter wurden enthüllt', iMemorized: 'Ich habe memorisiert', needMoreTime: 'Mehr Zeit nötig', tapToReveal: 'Tippen zum Enthüllen', timeElapsed: 'Zeit: {seconds}s', verseComplete: 'Vers memoriert! ✨', nextReview: 'Nächste Erinnerung: in {days} Tag{e}' },
  review: { todayReviews: 'Heutige Überprüfungen', overdue: 'Überfällig', dueSoon: 'Bald fällig', totalDue: '{count} fällig', estimatedTime: '~{minutes} Min', startReview: 'Überprüfung starten', iRecalled: 'Ich habe recalled', almost: 'Fast', forgot: 'Vergessen', correct: 'Richtig!', summary: 'Sitzungs-Zusammenfassung', easy: 'Einfach', hard: 'Schwer' },
  progress: { yourProgress: 'Dein Fortschritt', versesMemorized: 'Vers{e} memoriert{e}', inProgress: 'In Progress', toReview: 'Zu Überprüfen', streak: 'Serie', retention: 'Beziehung', thisWeek: 'Diese Woche', recentVerses: 'Letzte Verse', needsStrengthening: 'Braucht Stärkung', mastered: 'Meisterhaft' },
  settings: { settings: 'Einstellungen', uiLanguage: 'Sprache der Oberfläche', bibleTranslation: 'Bibelübersetzung', theme: 'Thema', light: 'Hell', dark: 'Dunkel', dataManagement: 'Daten & Speicherung', storageUsed: 'Speicher verwendet', exportData: 'Daten exportieren', about: 'Über', version: 'Version', documentation: 'Dokumentation', resetProgress: 'Fortschritt zurücksetzen', resetConfirmTitle: 'Bist du sicher?', resetConfirmText: 'Dies wird ALLE deine memorisierten Verse und Historie löschen.', typeConfirm: 'Tippe LÖSCHEN zur Bestätigung' },
  errors: { translationReset: 'Übersetzung auf LSG zurückgesetzt', verseNotFound: 'Vers in dieser Übersetzung nicht verfügbar', wasmFailed: 'Überprüfungsmotor deaktiviert. Vereinfachter Algorithmus aktiviert.', databaseCorrupt: 'Datenbank beschädigt. Wiederherstellung läuft...', unknownError: 'Ein unerwarteter Fehler ist aufgetreten' },
} as const;
