name: Build APK Debug Rapid

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install
      run: npm ci

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android
      uses: android-actions/setup-sdks@v2
      with:
        cmdline-tools-version: latest
        platforms: android-34
        build-tools: 35.0.0

    - name: Accept licenses
      run: yes | sdkmanager --licenses

    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug
        cd ..

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: versyflow-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
